name: Android CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
          distribution: 'adopt'
          java-version: '21'

    - name: Create cmdline-tools directory
      run: |
        mkdir -p $ANDROID_HOME/cmdline-tools

    - name: Change to cmdline-tools directory
      run: |
        cd $ANDROID_HOME/cmdline-tools

    - name: Download cmdline-tools
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip

    - name: Unzip cmdline-tools
      run: |
        unzip cmdline-tools.zip

    - name: Move cmdline-tools to latest
      run: |
        mv cmdline-tools $ANDROID_HOME/cmdline-tools/latest

    - name: Remove cmdline-tools zip file
      run: |
        rm cmdline-tools.zip

    - name: Set ANDROID_HOME and update PATH
      run: |
        echo "ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
        echo "PATH=$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools:$PATH" >> $GITHUB_ENV

    - name: Verify ANDROID_HOME
      run: |
        echo $ANDROID_HOME

    -  name: List AVDs before creation
       run: |
         adb version

    - name: Install emu
      run: |
           sudo apt install google-android-emulator-installer

    - name: emu Version
      run: |
           emulator -version

    # - name: Create AVD
    #   run: |
    #     $ANDROID_HOME/tools/bin/avdmanager create avd -n test -k "system-images;android-34;google_apis;x86_64"

    # - name: List AVDs after creation
    #   run: |
    #        adb version


    # - name: Start Emulator
    #   run: |
    #     nohup $ANDROID_HOME/emulator/emulator -avd test -no-window -gpu swiftshader_indirect -no-snapshot &

    # - name: Wait for Emulator device
    #   run: |
    #     $ANDROID_HOME/platform-tools/adb -e wait-for-device

    # - name: List adb devices (after emulator startup)
    #   run: |
    #     $ANDROID_HOME/platform-tools/adb devices
