name: Android CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Remove Old SDK to Prevent Conflicts
      run: |
        rm -rf $HOME/Android/Sdk
        mkdir -p $HOME/Android/Sdk

    - name: Set ANDROID_HOME and Update PATH
      run: |
        echo "ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
        echo "PATH=$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$PATH" >> $GITHUB_ENV
        echo "export ANDROID_HOME=$HOME/Android/Sdk" >> ~/.bashrc
        echo "export PATH=$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> ~/.bashrc
        source ~/.bashrc

    - name: Install SDK Command Line Tools
      run: |
        mkdir -p $ANDROID_HOME/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        rm cmdline-tools.zip

    - name: Install ADB and Platform Tools
      run: |
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
        sdkmanager --install "platform-tools"
        sdkmanager --install "emulator"
        sdkmanager --install "system-images;android-34;google_apis;x86_64"
        yes | sdkmanager --licenses
        chmod +x $ANDROID_HOME/platform-tools/adb
        chmod +x $ANDROID_HOME/emulator/emulator

    - name: Verify ADB is Installed
      run: |
        ls -la $ANDROID_HOME/platform-tools/
        echo "Checking ADB Version..."
        $ANDROID_HOME/platform-tools/adb version || echo "ADB still not found!"

    - name: Ensure ADB is in PATH
      run: |
        echo "Checking PATH for ADB..."
        which adb || echo "ADB not found in PATH!"
        export PATH=$ANDROID_HOME/platform-tools:$PATH
        echo "Retrying ADB version..."
        adb version || echo "ADB command still not found!"

    - name: Create Android Virtual Device (AVD)
      run: |
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
        echo "no" | avdmanager create avd -n test -k "system-images;android-34;google_apis;x86_64" --device "pixel_4"

    - name: List Available AVDs
      run: avdmanager list avd || echo "No AVDs available!"

    - name: Start Emulator
      run: |
        export PATH=$ANDROID_HOME/emulator:$PATH
        nohup emulator -avd test -no-window -no-audio -no-boot-anim -accel on &

    - name: Wait for Emulator to Boot
      run: adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 5; done'

    - name: Verify ADB Again
      run: adb devices || echo "ADB still not working!"
