name: Android CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adoptopenjdk'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-version: '30'

    - name: Create Android Emulator
      run: |
        echo "no" | $ANDROID_HOME/tools/bin/sdkmanager --licenses
        $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-30;google_apis;x86_64"
        echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n Pixel_3_API_30 -k "system-images;android-30;google_apis;x86_64" --force

    - name: Start Emulator
      run: |
        nohup $ANDROID_HOME/emulator/emulator -avd Pixel_3_API_30 -gpu swiftshader_indirect -no-snapshot &
        $ANDROID_HOME/platform-tools/adb wait-for-device

    - name: Run tests
      run: ./gradlew test
