name: Android CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Set ANDROID_HOME and Update PATH
      run: |
        echo "ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
        echo "PATH=$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$PATH" >> $GITHUB_ENV
        echo "export ANDROID_HOME=$HOME/Android/Sdk" >> ~/.bashrc
        echo "export PATH=$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> ~/.bashrc
        source ~/.bashrc

    - name: Manually Download Command Line Tools
      run: |
        mkdir -p $ANDROID_HOME/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        rm cmdline-tools.zip

    - name: Manually Download & Extract Platform Tools (ADB)
      run: |
        wget https://dl.google.com/android/repository/platform-tools-latest-linux.zip -O platform-tools.zip
        unzip platform-tools.zip -d $ANDROID_HOME
        rm platform-tools.zip
        ls -la $ANDROID_HOME/platform-tools

    - name: Ensure ADB is Installed and Working
      run: |
        chmod +x $ANDROID_HOME/platform-tools/adb
        export PATH=$ANDROID_HOME/platform-tools:$PATH
        which adb || echo "ADB not found in PATH!"
        adb version || echo "ADB command still not found!"
        adb devices || echo "ADB command still not found!"

    - name: check adb devices
      run: | 
          chmod +x $ANDROID_HOME/platform-tools/adb
          export PATH=$ANDROID_HOME/platform-tools:$PATH
          adb devices || not found


    - name: install emulator
      run: sudo apt install google-android-emulator-installer

    - name: Verify emu
      run: emulator -list-avds
      
    - name: Verify emu
      run: sudo apt install google-android-cmdline-tools-1.0-installer

    - name: Accept Licenses
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      
    - name: Create AVD
      run: |
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update

        sudo $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "system-images;android-34;google_apis;x86_64"

        
        $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n test -k "system-images;android-34;google_apis;x86_64"

    - name: Verify AVD Creation
      run: |
        $ANDROID_HOME/emulator/emulator -list-avds




    # - name: sreate emulator image
    #   run: sdkmanager --install "system-images;android-34;google_apis;x86_64"
    #       avdmanager create avd -n my_avd -k "system-images;android-34;google_apis;x86_64"




