name: Android CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Android SDK
      run: |
        sudo apt update
        sudo apt install -y android-sdk
        echo "y" | sdkmanager --licenses
        sdkmanager "platforms;android-34" "system-images;android-34;google_apis;x86_64"

    - name: Create Emulator AVD
      run: |
        echo no | avdmanager create avd -n Pixel_3_API_35 -k "system-images;android-34;google_apis;x86_64"

    - name: Start Emulator
      run: |
        nohup $ANDROID_HOME/emulator/emulator -avd Pixel_3_API_35 -no-window -gpu swiftshader_indirect -no-snapshot &
        $ANDROID_HOME/platform-tools/adb -e wait-for-device

    - name: Run Tests
      run: |
        ./gradlew test
