name: Android UI Tests

on: [push, pull_request]

jobs:
  ui-tests:
    name: UI Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        api-level: [28]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Install Android SDK
        uses: android-actions/setup-android@v2
      - name: Run sanity tests on API ${{ matrix.api-level }}
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86
          profile: Nexus 5X
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: |
            adb root
            adb logcat -c
            touch emulator.log
            chmod 777 emulator.log
            adb logcat >> emulator.log &
            ./gradlew connectedAndroidTest || (adb pull /storage/emulated/0/Pictures/failure_screenshots && exit 1)
      - name: Upload Test Report Log
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: uitest-error-results
          path: |
            emulator.log
            failure_screenshots/
