
name: CI CD

on:
  push:
    branches:
      - main
jobs:
#  lint:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout the code
#        uses: actions/checkout@v4  #fetch code from github

#      - name: make gradle executable
#        run: chmod +x ./gradlew  #ensure permissions with gradle
#
#      - name: Run android lint
#        run: ./gradlew lint   #Start Lint to detect code quality
#
#      - name: Upload lint Report
#        uses: actions/upload-artifact@v4 # Upload artifact
#        with:
#          name: Lint Report
#          path: app/build/reports/lint-results-debug.html
#
#  unit-test:
#    needs:
#      - lint
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout the code
#        uses: actions/checkout@v4
#
#      - name: Make gradle executable
#        run: chmod +x ./gradlew
#
#      - name: Run Unit Testing
#        run: ./gradlew test
#
#      - name: Upload test report
#        uses: actions/upload-artifact@v4
#        with:
#          name: unit-test-report
#          path: app/build/reports/tests/testDebugUnitTest/

  instumentation-test:
#    needs:
#      - unit-test
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 30 ]  # Define API level
        target: [ google_apis ]
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Make Gradle executable
          run: chmod +x ./gradlew

        - name: Set up Java JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'

        - name: Restart ADB to avoid connection issues
          run: |
            adb kill-server
            adb start-server

        - name: Run Emulator for Instrumentation Tests
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: ${{ matrix.api-level }}
            target: ${{ matrix.target }}
            arch: x86_64
            profile: Nexus 6
            emulator-options: "-no-window -gpu swiftshader_indirect -no-audio -no-boot-anim -memory 4096"
            disable-animations: true
            script: ./gradlew connectedCheck

        - name: Wait for Emulator to Boot
          run: |
            adb wait-for-device
            boot_status=""
            while [ "$boot_status" != "1" ]; do
              sleep 5
              boot_status=$(adb shell getprop sys.boot_completed | tr -d '\r')
              echo "Waiting for emulator to fully boot..."
            done
            echo "Emulator is ready!"

        - name: Stop Emulator (if running)
          run: |
            if adb devices | grep -q "emulator-5554"; then
              adb -s emulator-5554 emu kill
              echo "Emulator stopped."
            else
              echo "Emulator not running, skipping kill step."
            fi

        - name: Upload Test Report
          uses: actions/upload-artifact@v4
          with:
            name: instrumentation-test-report
            path: app/build/reports/androidTests/connected/

  static-code-analysis:
    needs:
      - instumentation-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Setup JDK !1
        uses: actions/setup-java@v4
        with:
          java-version: 11

      - name: Run sonarclud scan
        run: ./gradlew sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }}

        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

