
name: CI CD

on:
  push:
    branches:
      - main
jobs:
#  lint:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout the code
#        uses: actions/checkout@v4  #fetch code from github

#      - name: make gradle executable
#        run: chmod +x ./gradlew  #ensure permissions with gradle
#
#      - name: Run android lint
#        run: ./gradlew lint   #Start Lint to detect code quality
#
#      - name: Upload lint Report
#        uses: actions/upload-artifact@v4 # Upload artifact
#        with:
#          name: Lint Report
#          path: app/build/reports/lint-results-debug.html
#
#  unit-test:
#    needs:
#      - lint
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout the code
#        uses: actions/checkout@v4
#
#      - name: Make gradle executable
#        run: chmod +x ./gradlew
#
#      - name: Run Unit Testing
#        run: ./gradlew test
#
#      - name: Upload test report
#        uses: actions/upload-artifact@v4
#        with:
#          name: unit-test-report
#          path: app/build/reports/tests/testDebugUnitTest/

   instumentation-test:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Start ADB Server
      run: $ANDROID_HOME/platform-tools/adb start-server

    - name: Start Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis
        arch: arm64-v8a
        profile: pixel_2
        cores: 2  # Reduced CPU cores
        avd-name: test
        force-avd-creation: true
        emulator-boot-timeout: 600
        emulator-port: 5554
        emulator-options: -no-window -gpu off -no-snapshot -noaudio -no-boot-anim  # Disabled GPU
        disable-animations: true
        disable-spellchecker: false
        disable-linux-hw-accel: true  # Disabled hardware acceleration
        enable-hw-keyboard: false
        channel: stable
        script: ./gradlew connectedCheck

    - name: Configure AVD RAM Size
      run: echo "hw.ramSize=3072" >> /Users/runner/.android/avd/test.avd/config.ini
       
          
          
            

   static-code-analysis:
    needs:
      - instumentation-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Setup JDK !1
        uses: actions/setup-java@v4
        with:
          java-version: 11

      - name: Run sonarclud scan
        run: ./gradlew sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }}

        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

