
name: CI CD

on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2  #fetch code from github

      - name: make gradle executable
        uses: chmod +x ./gradlew  #ensure permissions with gradle

      - name: Run android lint
        run: ./gradlew lint   #Start Lint to detect code quality

      - name: Upload lint Report
        uses: actions/upload-artifact@v2
        with:
            name: Lint Report
            path: app/build/reports/lint-results-debug.html

