name: CI  # Name of the workflow
on:
  push:
    branches: [ main ]  # Runs when code is pushed to the master branch
  pull_request:
    branches: [ main ]  # Runs when a pull request targets the master branch
  workflow_dispatch:  # Allows manual triggering of the workflow
jobs:
  static-code-analysis:  # Job for running SonarCloud (Static Code Analysis)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Set up JDK 17  # SonarCloud requires Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Run SonarCloud Scan  # Runs SonarCloud to analyze code quality
        run: ./gradlew app:sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
